fix https+auth bug
hugegraph/hugegraph-common pull request #57
Opened 2020-11-16 03:36 UTC by zhoney

Change-Id: Icbef2f43471fe260fde6106537eaa4255ffc823e

2020-11-16 06:31 UTC, javeme requested changes

2020-11-16 06:31 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        final Registry<ConnectionSocketFactory> registry =
remove "final"

2020-11-16 06:31 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +                        new PoolingHttpClientConnectionManager(registry));
missing PoolingHttpClientConnectionManager params

2020-11-16 08:38 UTC, javeme approved these changes

2020-11-16 08:48 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String trustStorePass = (String) conf.getProperty("trustStorePassword");
check not null

2020-11-16 11:58 UTC, javeme approved these changes

2020-11-17 09:19 UTC, Linary approved these changes

2020-11-17 09:19 UTC, merged