Implement PausableScheduledThreadPool
hugegraph/hugegraph-common pull request #61
Opened 2021-01-21 13:10 UTC by Linary

2021-01-22 09:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +    private boolean paused = false;
set volatile if not all access are synchronized

2021-01-22 09:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +    protected synchronized void beforeExecute(Thread t, Runnable r) {
don't lock super.beforeExecute()

2021-01-22 09:11 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +        if (this.paused) {
unneeded

2021-01-22 14:27 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +        synchronized (this) {
move `this.paused = false;` into synchronized block to avoid race between resumeSchedule and resumeSchedule

2021-01-22 14:27 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +        synchronized (this) {
keep all paused writing synchronized

2021-01-26 04:19 UTC, javeme submitted a review, later dismissed

2021-01-26 12:41 UTC, houzhizhen approved these changes

2021-01-30 08:49 UTC, zhoney approved these changes

2021-02-01 03:36 UTC, javeme approved these changes

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(4500);
4500L

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        }, 2, 2, TimeUnit.SECONDS);
2, 2 -> 2L, 2L

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(2000);
2000L

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(2000);
2000L

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        }, 2, 2, TimeUnit.SECONDS);
ditto

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(4500);
ditto

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(2000);
ditto

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        Thread.sleep(2000);
ditto

2021-02-01 07:33 UTC, houzhizhen commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +        executor.awaitTermination(3, TimeUnit.SECONDS);
ditto

2021-02-01 08:35 UTC, houzhizhen submitted a review, later dismissed

2021-02-01 08:37 UTC, javeme approved these changes

2021-02-01 08:40 UTC, zhoney submitted a review, later dismissed

2021-02-02 05:24 UTC, javeme requested changes

2021-02-02 05:24 UTC, javeme commented on src/main/java/com/baidu/hugegraph/threadpool/PausableScheduledThreadPool.java
> +/*
prefer to move to concurrent package

2021-02-02 05:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/unit/threadpool/PausableScheduledThreadPoolTest.java
> +/*
ditto

2021-02-02 06:21 UTC, zhoney approved these changes

2021-02-02 09:11 UTC, javeme commented
ci error
![image](https://user-images.githubusercontent.com/9625821/106577708-a7776500-6579-11eb-8240-d6359661926b.png)

2021-02-03 03:26 UTC, javeme approved these changes

2021-02-03 06:23 UTC, zhoney requested changes

2021-02-03 06:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/unit/UnitTestSuite.java
> +//    LockManagerTest.class,
keep origin

2021-02-03 13:47 UTC, zhoney approved these changes

2021-02-03 14:01 UTC, javeme approved these changes

2021-02-03 14:03 UTC, merged