add UnitUtil class
hugegraph/hugegraph-common pull request #66
Opened 2021-03-07 15:42 UTC by javeme

Change-Id: Ic1a434fda3a051c10e37190aaab22e9db466bb23

2021-03-17 12:17 UTC, Linary submitted a review, later dismissed

2021-03-17 12:23 UTC, zhoney requested changes

2021-03-17 12:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/unit/util/UnitUtilTest.java
> +        // overflow
Overflow

2021-03-17 12:23 UTC, zhoney commented on src/test/java/com/baidu/hugegraph/unit/util/UnitUtilTest.java
> +        // invalid unit
ditto

2021-03-19 12:06 UTC, zhoney approved these changes

2021-03-19 12:44 UTC, Linary approved these changes

2021-03-19 12:44 UTC, merged

2021-03-21 15:30 UTC, aidanBurton commented on src/test/java/com/baidu/hugegraph/unit/util/UnitUtilTest.java
> +        Assert.assertEquals((long) (Bytes.KB * 3.14),
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [CNT: Rough value of known constant found (CNT_ROUGH_CONSTANT_VALUE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#cnt-rough-value-of-known-constant-found-cnt-rough-constant-value).
It's recommended to use the predefined library constant for code clarity and better precision.