add some test cases for util package
hugegraph/hugegraph-common pull request #70
Opened 2021-04-07 05:44 UTC by javeme

Change-Id: I39b457c2a7a338a909b3aa0ba8ff4a8b5057b339

2021-04-07 05:44 UTC, javeme commented
Before adding test cases:
![image](https://user-images.githubusercontent.com/9625821/113816383-5bc67f00-97a7-11eb-98a5-5e0aacf7d41e.png)

2021-04-07 05:48 UTC, javeme commented
After adding test cases:
![image](https://user-images.githubusercontent.com/9625821/113816810-e9a26a00-97a7-11eb-987a-c93cedbf7163.png)

2021-04-07 07:02 UTC, Linary requested changes

2021-04-07 11:46 UTC, javeme commented on src/main/java/com/baidu/hugegraph/util/CollectionUtil.java
> +            E.checkArgument(from >= 0,
to keep same style with "if (to < 0)"

2021-04-12 08:07 UTC, corgiboygsj approved these changes

2021-04-12 08:10 UTC, houzhizhen commented on src/main/java/com/baidu/hugegraph/util/CollectionUtil.java
> +        if (to < 0) {
"if (to < 0)" => "if (to < from)". IllegalArgumentException will be thrown if  to < from。

2021-04-12 08:24 UTC, houzhizhen approved these changes

2021-04-12 08:27 UTC, Linary approved these changes

2021-04-12 08:28 UTC, merged