add Auth Context to store request header(Authorization)
hugegraph/hugegraph-common pull request #76
Opened 2021-06-15 11:42 UTC by corgiboygsj

2021-06-15 12:01 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +    private void buildAuthToRequest(Builder builder) {
attachAuthToRequest

2021-06-16 03:53 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +            builder.header(HttpHeaders.AUTHORIZATION, auth);
can add test case to assert it's effective？

2021-06-16 04:25 UTC, Linary requested changes

2021-06-16 04:25 UTC, Linary commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String auth = getAuthContext();
this.getAuthContext()

2021-06-16 04:25 UTC, Linary commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String auth = getAuthContext();
Need check auth != null ?

2021-06-16 09:10 UTC, corgiboygsj commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String auth = getAuthContext();
not necessary

2021-06-16 14:04 UTC, javeme commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String auth = getAuthContext();
StringUtils.isNotEmpty can accept null?

2021-06-16 14:16 UTC, corgiboygsj commented on src/main/java/com/baidu/hugegraph/rest/AbstractRestClient.java
> +        String auth = getAuthContext();
> StringUtils.isNotEmpty can accept null?

yep

2021-06-17 11:27 UTC, Linary requested changes

2021-06-17 11:27 UTC, Linary commented on pom.xml
> +    <version>1.8.9</version>
line 290 `<Implementation-Version>1.8.8.0</Implementation-Version> ` also need modify to 1.8.9.0

2021-06-18 11:46 UTC, javeme commented
to fix codecov

2021-06-22 06:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/unit/rest/RestClientTest.java
> +        Assert.assertEquals(200, result.status());
assert the builder contains AUTHORIZATION header

2021-06-22 06:24 UTC, javeme commented on src/test/java/com/baidu/hugegraph/unit/rest/RestClientTest.java
> +        result = client.delete("test", "id");
test for each method:

1. setContext with different token
2. do get/post/put/delete
3. assert AUTHORIZATION header is expected

and also test it after resetAuthContext()

2021-06-23 08:26 UTC, javeme submitted a review, later dismissed

2021-06-24 07:56 UTC, Linary approved these changes

2021-06-24 07:59 UTC, javeme approved these changes

2021-06-24 08:00 UTC, merged